In [1]:
import numpy as np

In [18]:
x1 = np.round(np.random.randn(25) * 5 + 5, 3)

In [19]:
x2 = np.round(np.random.randn(25) * 5, 3)

In [37]:
x3 = np.round(np.random.randn(25) * 5, 3)

In [20]:
import scipy.stats
print scipy.stats.ttest_ind(x1, x2)

(3.3134831695504219, 0.001757961682260456)


In [22]:
x1

array([  8.51 ,  11.956,  12.614,   8.037,   7.032,  -4.054,   6.833,
        10.379,   6.468,   5.12 ,   2.965,   0.703,  18.982,   8.226,
         1.846,  11.849,   5.241,  11.916,   8.66 ,   6.6  ,   8.736,
         6.211,   7.627,   3.138,   8.611])

In [23]:
x2

array([  6.813,  -4.885,   4.714,   2.638,  -9.236,   8.857,  14.112,
        -5.521,   5.07 ,   8.812,   4.362,   1.025,  -6.977,  -2.642,
        -3.629,  -1.49 ,  -6.695,  -0.288,   0.565,   7.183,   0.829,
        10.003,   4.842,   2.254,  13.568])

In [38]:
x3

array([  4.86 ,  -0.1  ,  -0.422,  -2.604,  -4.16 ,   0.074,   5.109,
         4.882,   3.517,  11.881,  -7.552,  -0.674,   2.048,   1.017,
         3.978,  -3.119,  10.277,  -2.903,   4.618,  -4.941,   7.597,
        -6.34 ,  -0.906,   3.008,   2.513])

In [44]:
y1 = np.round(x1 * 2 + 3 + np.random.randn(25)*10, 3)

In [45]:
scipy.stats.pearsonr(x1, y1)

(0.68211700004978704, 0.00017287143307755218)

In [46]:
y1

array([ 31.632,  27.83 ,  42.293,  20.808,  35.741,   6.197,  29.549,
        31.029,   3.497,   6.446,  -3.054, -10.016,  25.008,   7.998,
        -3.806,  23.126,   5.606,  27.181,  18.44 ,  16.105,  17.236,
        16.886,  29.777,   9.859,  20.154])

In [28]:
eff = np.absolute(x1.mean() - x2.mean()) / np.sqrt(np.square(x1.std()) + np.square(x2.std()))

In [29]:
eff

0.67636191972487114

In [30]:
x2.std()

6.2598320800481542

In [32]:
np.square(x1.std())/10 + np.square(x2.std())/10

5.9037380732799996

In [34]:
np.sqrt(10*np.square(x1.std())/20 + 10*np.square(x2.std())/20)

5.4331105608481778

In [35]:
x1.mean()

7.3682399999999992

In [36]:
x1.std()

4.455545203720864